Repository sifive/freedom-metal, pull requests merged in 2019-07, with the labels that each got.

#120 Support multiple callbacks for a clock rate change
  metal/clock.h
  metal/drivers/sifive_spi0.h
  metal/drivers/sifive_uart0.h
  src/clock.c
  src/drivers/sifive_fe310-g000_pll.c
  src/drivers/sifive_spi0.c
  src/drivers/sifive_uart0.c
Labels: API CHANGE

#115 Add API to check for dcache and flush
  Makefile.am
  Makefile.in
  metal/cache.h
  src/cache.c
Labels: NEW API

#121 Improve uart api
  metal/tty.h
  metal/uart.h
  src/drivers/sifive_uart0.c
  src/tty.c
  src/uart.c
Labels: API CHANGE, NEW API

#122 Add new APIs for GPIO input/interrupt functions
  metal/gpio.h
  src/drivers/sifive_gpio0.c
  src/gpio.c
Labels: API CHANGE, NEW API

#123 Adds Watchdog API and drivers for sifive,wdog0 and FE310-G000 LFROSC
  Makefile.am
  Makefile.in
  metal/drivers/sifive_fe310-g000_lfrosc.h
  metal/drivers/sifive_wdog0.h
  metal/watchdog.h
  src/drivers/sifive_fe310-g000_lfrosc.c
  src/drivers/sifive_wdog0.c
  src/watchdog.c
Labels: NEW API
